# Generated by Django 4.2.6 on 2023-11-01 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('13c6a66d-ffe7-45af-8aca-5e133604585a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
