# Generated by Django 4.2.6 on 2023-11-04 08:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_timingtodo_user_todo_user_alter_timingtodo_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timingtodo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c9153eef-8a30-4e46-a794-737d0dfce44e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c9153eef-8a30-4e46-a794-737d0dfce44e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
